#!/usr/bin/with-contenv bash

if [ "$fpm" == "true" ]; then
  echo "Performing convertion to use sockets"

  if [ ! -f /etc/php7/php-fpm.d/www.conf.original ]; then
    cp /etc/php7/php-fpm.d/www.conf /etc/php7/php-fpm.d/www.conf.original
  fi

  # TODO: Check if settings catch
  # enable PHP-FPM
  sed -i "s#listen = 127.0.0.1:9000#listen = '/var/run/php7-fpm.sock'#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#;listen.owner = nobody#listen.owner = abc#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#;listen.group = abc#listen.group = abc#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#;listen.mode = nobody#listen.mode = 0660#g" /etc/php7/php-fpm.d/www.conf
  # set our recommended defaults
  sed -i "s#pm = dynamic#pm = ondemand#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#pm.max_children = 5#pm.max_children = 4000#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#pm.start_servers = 2#;pm.start_servers = 2#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#;pm.process_idle_timeout = 10s;#pm.process_idle_timeout = 10s;#g" /etc/php7/php-fpm.d/www.conf
  sed -i "s#;pm.max_requests = 500#pm.max_requests = 0#g" /etc/php7/php-fpm.d/www.conf

  # change nginx confs
  sed -i "s#fastcgi_pass 127.0.0.1:9000;#fastcgi_pass unix:/var/run/php7-fpm.sock;#g" /config/nginx/site-confs/healthcheck
  sed -i "s#fastcgi_pass 127.0.0.1:9000;#fastcgi_pass unix:/var/run/php7-fpm.sock;#g" /config/nginx/site-confs/default
fi